/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Angazovanje;
import domen.Predmet;
import domen.Profesor;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Operacija;
import transfer.Odgovor;
import transfer.Zahtev;

/**
 *
 * @author Mafija
 */
public class DijalogAngazovanjeIzmena extends javax.swing.JDialog {

    Angazovanje a = null;
    Profesor p;
    
    /**
     * Creates new form DijalogAngazovanje
     */
    public DijalogAngazovanjeIzmena(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniPredmete();
        //popuniPreofesore();
    }

    public void setP(Profesor p) {
        this.p = p;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelaPredmet = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPredmeti = new javax.swing.JComboBox();
        txtDatum = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnIzmena = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelaPredmet.setText("Predmet");

        jLabel2.setText("Datumn");

        cmbPredmeti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnIzmena.setText("Izmeni");
        btnIzmena.setEnabled(false);
        btnIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzmena))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(txtDatum))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelaPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(cmbPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelaPredmet)
                    .addComponent(cmbPredmeti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzmena))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        
        Predmet predmet = (Predmet) cmbPredmeti.getSelectedItem();
        Date datum = null;
        
        try {
            datum = sdf.parse(txtDatum.getText());
        } catch (ParseException ex) {
            Logger.getLogger(DijalogAngazovanjeIzmena.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Datum mora biti u formatu dd.MM.yyyy");
            return;
        }
        
        GlavnaForma gf = (GlavnaForma) getParent();
        
        gf.unesiNovoAngazovanjeZaIzmenu(predmet, p, datum);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmenaActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
       
        Date datum = null;
        try {
            datum = sdf.parse(txtDatum.getText());
        } catch (ParseException ex) {
            Logger.getLogger(DijalogAngazovanjeIzmena.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Datum mora biti u formatu dd.MM.yyyy");
            return;
        }
        
        GlavnaForma gf = (GlavnaForma) getParent();
        a.setDatum(datum);
        
        gf.unesiIzmenuAngazovanja(a);
        this.dispose();
    }//GEN-LAST:event_btnIzmenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DijalogAngazovanjeIzmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DijalogAngazovanjeIzmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DijalogAngazovanjeIzmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DijalogAngazovanjeIzmena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DijalogAngazovanjeIzmena dialog = new DijalogAngazovanjeIzmena(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmena;
    private javax.swing.JComboBox cmbPredmeti;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelaPredmet;
    private javax.swing.JTextField txtDatum;
    // End of variables declaration//GEN-END:variables

    private void popuniPredmete() {
        Zahtev zahtev = new Zahtev(Operacija.VRATI_PREDMETE, null);
        
        Komunikacija.getKomunikacija().posaljiZahtev(zahtev);
        
        Odgovor odg = Komunikacija.getKomunikacija().primiOdgovor();
        
        ArrayList<Predmet> lista = (ArrayList<Predmet>) odg.getOdgovor();
        
        cmbPredmeti.removeAllItems();
        
        for (Predmet predmet : lista) {
            cmbPredmeti.addItem(predmet);
        }
    }


    void srediFormuZaIzmenu(Angazovanje a) {
        btnDodaj.setEnabled(false);
        btnIzmena.setEnabled(true);
        this.a = a;
        
        cmbPredmeti.setVisible(false);
        labelaPredmet.setVisible(false);
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatum.setText(sdf.format(a.getDatum()));
    }

   
}
